### ISSUE TITLE
JMS Tutorial building native executive with Docker

### ISSUE THREAD

**Issue by aslihanilgin** [amqphub/quarkus-qpid-jms#16]
I am following [this](https://quarkus.io/guides/jms#get-it-running) tutorial.

In the **Running Native** step towards the end, building the native executable with Docker produces the following error:

`[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code was 137 which indicates an out of memory error. Consider increasing the Xmx value for native image generation by setting the "quarkus.native.native-image-xmx" property`

I tried setting up the property **quarkus.native.native-image-xmx** to 8GB and 10GB to see if it would help but it did not fix the issue. 

I am on macOS Big Sur Version 11.6 and using Docker 3.5.2 (66501).

**Comment by gemmellr** [comment]
I believe the build can also fail there due to the docker process itself having insufficient memory, something I think I have seen mention of for Mac OS specifically in the past.
