### ISSUE TITLE
Azure Managed ID

### ISSUE THREAD

**Issue by RJJdeVries** [amqphub/quarkus-qpid-jms#20]
Hi there,

Not an issue, but more of a question. Is it also possible to use Azure Managed Identity with Qpid? I saw a property called Client ID, but when I configure that with the client ID of my Managed Identity, I get the following error:

Exception in thread "pool-14-thread-1" javax.jms.JMSSecurityRuntimeException: Unauthorized access. 'Listen' claim(s) are required to perform this operation.

I double checked the permissions, and the Managed ID has access to the specific Service Bus -> Queue.

**Comment by gemmellr** [comment]
I'll need to direct you to Microsoft for such questions, its not something I'm familiar with. Their JMS guides cover how to use the JMS client with Service Bus, either via their delegating factory bits (which shouldnt be doing anything you couldnt yourself if needed), or directly.

https://docs.microsoft.com/en-us/azure/service-bus-messaging/how-to-use-java-message-service-20
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp
