### ISSUE TITLE
Feature request : support SSL certificate

### ISSUE THREAD

**Issue by zhang-hongjie** [amqphub/quarkus-qpid-jms#9]
Like `username + password`, we can support   SSL `tls.crt + tls.key`, or maybe SSL `*.p12 + keypass`

for example:  https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/amqp/amqp.html#amqp-customization
```
@Produces
@Named("my-named-options")
public AmqpClientOptions getNamedOptions() {
    // You can use the produced options to configure the TLS connection
    PemKeyCertOptions keycert = new PemKeyCertOptions()
        .addCertPath("./tls/tls.crt")
        .addKeyPath("./tls/tls.key");
    PemTrustOptions trust =
        new PemTrustOptions().addCertPath("./tlc/ca.crt");

    return new AmqpClientOptions()
        .setSsl(true)
        .setPemKeyCertOptions(keycert)
        .setPemTrustOptions(trust)
        .addEnabledSaslMechanism("EXTERNAL")
        .setHostnameVerificationAlgorithm("")
        .setConnectTimeout(30000)
        .setReconnectInterval(5000)
        .setContainerId("my-container");
}
```

**Comment by gemmellr** [comment]
Can you elaborate on the specifics of what you are requesting?

**Comment by zhang-hongjie** [comment]
> Can you elaborate on the specifics of what you are requesting?

Hello, I have added the specifics. do you think it's good now ?

**Comment by gemmellr** [comment]
The client is configured via it's URL options, which already allow for TLS config. Consult the clients documentation linked from the readme.

**Comment by gemmellr** [comment]
https://qpid.apache.org/releases/qpid-jms-0.54.0/docs/index.html#ssl-transport-configuration-options

**Comment by zhang-hongjie** [comment]
> https://qpid.apache.org/releases/qpid-jms-0.54.0/docs/index.html#ssl-transport-configuration-options

You are so kind, thanks.
